const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    entry: {
        vendor: [
            'react',
            'react-dom',
            'react-bind-handlers',
            'react-router',
            'react-router-dom',
            'react-bootstrap',
            'lodash',
            'redux',
            'redux-thunk',
            'jquery',
        ],
        index: path.join(__dirname, '../src', 'js', 'main')
    },

    stats: {
        colors: true,
        reasons: true,
        chunks: true
    },

    output: {
        path: path.resolve(__dirname, '../public', 'build'),
        filename: '[name][chunkhash].js',
    },

    module: {
        loaders: [
            {
                test: /\.json$/,
                loader: 'json-loader'
            },
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: {
                        loader: 'css-loader',
                        options: {
                            modules: true,
                            localIdentName: '[local]' // this is for keeping the name of classes in imported css files same
                            // with the hashed name generated by css-loader modules
                        }
                    }
                }),
            },
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015', 'react'],
                    plugins: ["transform-object-rest-spread"],
                }
            },
            {
                test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
                loaders: ['file-loader'],
            },
            {
                test: /\.(woff|woff2)$/,
                loaders: ['url-loader'],
            },
            {
                test: /\.(png|jpg|gif)$/,
                loaders: ['file-loader'],
            },
            {
                test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
                loaders: ['url-loader'],
            },
            {
                test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                loaders: ['url-loader'],
            }
        ]
    },

    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: 3,
        }),

        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, '../src', 'index.html'),
            title: 'Dynamic Html',
        }),

        new ExtractTextPlugin({
            filename: "styles.css",
            allChunks: true,
        }),

        //this is for removing './locale' not found error in momentjs.
        new webpack.ContextReplacementPlugin(/\.\/locale$/, 'empty-module', false, /js$/),
    ],

    resolve: {
        modules: [
            path.resolve(__dirname, '../'),
            'node_modules',
        ],
        extensions: ['.js', '.jsx', '.json']
    },
};